title: "hammad.dev"
description: "Machine learning notes, learning guides, and projects by Hammad Naeem."
url: "https://hammad-naeem1.github.io"
baseurl: "/fieldnotes"
timezone: "Asia/Karachi"
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
contact_email: "hammadconnect1@gmail.com"
github_url: "https://github.com/hammad-naeem1"
huggingface_username: "codehammad"
huggingface_url: "https://huggingface.co/codehammad"
discord_username: "hammad-naeem1"

collections:
  projects:
    output: true
    permalink: /portfolio/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

exclude:
  - "README.md"
  - "_templates"
